name: Auto Merge
run-name: ${{ github.sha }}
on: 
  pull_request:
    types: [closed]
jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Auto Merge
        run: |
          git fetch origin
          git checkout -b $GITHUB_HEAD_REF origin/$GITHUB_HEAD_REF
          git merge --allow-unrelated-histories $GITHUB_SHA -m "Merge $GITHUB_BASE_REF branch into $GITHUB_HEAD_REF by GitHub Actions"
          git push origin $GITHUB_HEAD_REF